### ISSUE TITLE
User should see the number of sets and time they have to do for an exercise

### ISSUE THREAD

**Issue by RogerJLeeJ18** [Take-A-Lap/HomeFit#28]
1. Client sends call to server to get exercsie info.
2. Server receives exercise name from request and queries the database for the exercise
3. Server parses the response from the database to look for the amount of sets and time of the exercise.
4. Server sends a response to the client

**Comment by jstrzesz** [comment]
is this cardio specific or is this for both cardio and strength-training?

**Comment by jstrzesz** [comment]
closed by accident
